export const DEFAULT = '/'
export const DASHBOARD = '/dashboard'
export const PRODUCTS = '/dashboard/products'
export const ORDERS = '/dashboard/orders'
export const USERS = '/dashboard/users'
export const COMING_SOON = '/coming-soon'
